import { FormSchema } from '/@/components/Form/index';
import { useI18n } from '/@/hooks/web/useI18n';
const { t } = useI18n();

export const rebateSports: FormSchema[] = [
  {
    field: 'field1',
    component: 'Input',
    label: t('common.IMSports'),
    componentProps: {
      placeholder: t('business.banner_tip'),
      addonAfter: '%',
    },
  },
  {
    field: 'field1',
    component: 'Input',
    label: t('common.SportsNum', [1]),
    componentProps: {
      placeholder: t('business.banner_tip'),
      addonAfter: '%',
    },
  },
  {
    field: 'field1',
    component: 'Input',
    label: t('common.SportsNum', [2]),
    componentProps: {
      placeholder: t('business.banner_tip'),
      addonAfter: '%',
    },
  },
];

export const rebateReal: FormSchema[] = [
  {
    field: 'field1',
    component: 'Input',
    label: t('common.agRealPerson'),
    componentProps: {
      placeholder: t('business.banner_tip'),
      addonAfter: '%',
    },
  },
  {
    field: 'field1',
    component: 'Input',
    label: t('common.LiveNum', [2]),
    componentProps: {
      placeholder: t('business.banner_tip'),
      addonAfter: '%',
    },
  },
  {
    field: 'field1',
    component: 'Input',
    label: t('common.LiveNum', [3]),
    componentProps: {
      placeholder: t('business.banner_tip'),
      addonAfter: '%',
    },
  },
];

export const rebateEle: FormSchema[] = [
  {
    field: 'field1',
    component: 'Input',
    label: t('common.PGElectronics'),
    componentProps: {
      placeholder: t('business.banner_tip'),
      addonAfter: '%',
    },
  },
  {
    field: 'field1',
    component: 'Input',
    label: t('common.ElectronicsNum', [2]),
    componentProps: {
      placeholder: t('business.banner_tip'),
      addonAfter: '%',
    },
  },
  {
    field: 'field1',
    component: 'Input',
    label: t('common.ElectronicsNum', [3]),
    componentProps: {
      placeholder: t('business.banner_tip'),
      addonAfter: '%',
    },
  },
];

export const realiy = [
  {
    game_type: '1',
    data: [
      {
        id: '101',
        en_name: 'EVO Casino',
        game_type: '1',
        zh_name: 'EVO真人',
        pt_name: 'EVO Casino',
        vn_name: 'EVO Casino',
        th_name: 'EVO Casino',
        name: 'EVO真人',
        rate: '16',
      },
    ],
  },
  {
    game_type: '3',
    data: [
      {
        id: '302',
        en_name: 'Slot EVO',
        game_type: '3',
        zh_name: 'EVO电子',
        pt_name: 'Slot EVO',
        vn_name: 'Slot EVO',
        th_name: 'Slot EVO',
        name: 'EVO电子',
        rate: '3',
      },
      {
        id: '301',
        en_name: 'Slot PG',
        game_type: '3',
        zh_name: 'PG电子',
        pt_name: 'Slot PG',
        vn_name: 'Slot PG',
        th_name: 'Slot PG',
        name: 'PG电子',
        rate: '3',
      },
    ],
  },
  {
    game_type: '4',
    data: [
      {
        id: '401',
        en_name: 'IM Sport',
        game_type: '4',
        zh_name: 'IM体育',
        pt_name: 'IM Sport',
        vn_name: 'IM Sport',
        th_name: 'IM Sport',
        name: 'IM体育',
        rate: '12',
      },
      {
        id: '412',
        en_name: 'AB Sport',
        game_type: '4',
        zh_name: 'AB体育',
        pt_name: 'AB Sport',
        vn_name: 'AB Sport',
        th_name: 'AB Sport',
        name: 'AB体育',
        rate: '2',
      },
      {
        id: '422',
        en_name: 'CD Sport',
        game_type: '4',
        zh_name: 'CD体育',
        pt_name: 'CD Sport',
        vn_name: 'CD Sport',
        th_name: 'CD Sport',
        name: 'CD体育',
        rate: '2',
      },
      {
        id: '432',
        en_name: 'EF Sport',
        game_type: '4',
        zh_name: 'EF体育',
        pt_name: 'EF Sport',
        vn_name: 'EF Sport',
        th_name: 'EF Sport',
        name: 'EF体育',
        rate: '2',
      },
    ],
  },
];

export const realiyNew = [
  {
    game_type: '1',
    data: [
      {
        id: '101',
        en_name: 'EVO Casino',
        game_type: '1',
        zh_name: 'EVO真人',
        pt_name: 'EVO Casino',
        vn_name: 'EVO Casino',
        th_name: 'EVO Casino',
        name: 'EVO真人',
        rate: '',
      },
    ],
  },
  {
    game_type: '4',
    data: [
      {
        id: '401',
        en_name: 'IM Sport',
        game_type: '4',
        zh_name: 'IM体育',
        pt_name: 'IM Sport',
        vn_name: 'IM Sport',
        th_name: 'IM Sport',
        name: 'IM体育',
        rate: '',
      },
    ],
  },
];

export const newRealiy = [
  {
    game_type: '1',
    data: [
      {
        id: '101',
        en_name: 'EVO Casino',
        game_type: '1',
        zh_name: 'EVO真人',
        pt_name: 'EVO Casino',
        vn_name: 'EVO Casino',
        th_name: 'EVO Casino',
        name: 'EVO真人',
        rate: '16',
      },
    ],
  },
  {
    game_type: '4',
    data: [
      {
        id: '401',
        en_name: 'IM Sport',
        game_type: '4',
        zh_name: 'IM体育',
        pt_name: 'IM Sport',
        vn_name: 'IM Sport',
        th_name: 'IM Sport',
        name: 'IM体育',
        rate: '12',
      },
      {
        id: '412',
        en_name: 'AB Sport',
        game_type: '4',
        zh_name: 'AB体育',
        pt_name: 'AB Sport',
        vn_name: 'AB Sport',
        th_name: 'AB Sport',
        name: 'AB体育',
        rate: '2',
      },
      {
        id: '422',
        en_name: 'CD Sport',
        game_type: '4',
        zh_name: 'CD体育',
        pt_name: 'CD Sport',
        vn_name: 'CD Sport',
        th_name: 'CD Sport',
        name: 'CD体育',
        rate: '2',
      },
      {
        id: '432',
        en_name: 'EF Sport',
        game_type: '4',
        zh_name: 'EF体育',
        pt_name: 'EF Sport',
        vn_name: 'EF Sport',
        th_name: 'EF Sport',
        name: 'EF体育',
        rate: '2',
      },
    ],
  },
];
//js 怎么根据realiy和realiyNew这两个数组对象做比较，如果realiyNew里没有realiy里的 game_type: '3'的数组元素，返回newRealiy

export const dataSet = [
  {
    id: '101',
    game_type: '1',
    name: t('common.evoRealPerson'),
    rate: '6',
  },
  {
    id: '302',
    game_type: '3',
    name: t('common.EVOElectronics'),
    rate: '6',
  },
  {
    id: '301',
    game_type: '3',
    name: t('common.PGElectronics'),
    rate: '6',
  },
  {
    id: '401',
    game_type: '4',
    name: t('common.IMSports'),
    rate: '6',
  },
];

export const dataSetSubmit = [
  {
    game_type: '1',
    data: [
      {
        name: t('common.evoRealPerson'),
        game_type: '1',
        rate: '6',
        id: '101',
      },
    ],
  },
  {
    game_type: '3',
    data: [
      {
        name: t('common.EVOElectronics'),
        rate: '6',
        id: '302',
      },
      {
        id: '301',
        game_type: '3',
        name: t('common.PGElectronics'),
        rate: '6',
      },
    ],
  },
  {
    game_type: '4',
    data: [
      {
        id: '401',
        game_type: '4',
        name: t('common.IMSports'),
        rate: '6',
      },
    ],
  },
];

//封装一个方法 js 怎么将dataSet转换为dataSetSubmit

export const att = {
  id: '101',
  en_name: 'EVO Casino',
  game_type: '1',
  zh_name: 'EVO真人',
  pt_name: 'EVO Casino',
  vn_name: 'EVO Casino',
  th_name: 'EVO Casino',
  name: 'EVO真人',
  rate: '10',
};

export const newAtt = [
  {
    id: '101',
    game_type: '1',
    name: 'EVO真人',
    rate: '9',
    en_name: 'EVO Casino',
    pt_name: 'EVO Casino',
    th_name: 'EVO Casino',
    vn_name: 'EVO Casino',
    zh_name: 'EVO真人',
  },
  {
    id: '301',
    game_type: '3',
    name: 'PG电子',
    rate: '13',
    en_name: 'Slot PG',
    pt_name: 'Slot PG',
    th_name: 'Slot PG',
    vn_name: 'Slot PG',
    zh_name: 'PG电子',
  },
  {
    id: '302',
    game_type: '3',
    name: 'EVO电子',
    rate: '13',
    en_name: 'Slot EVO',
    pt_name: 'Slot EVO',
    th_name: 'Slot EVO',
    vn_name: 'Slot EVO',
    zh_name: 'EVO电子',
  },
];

//js使用att的这一项，替换newAtt相同ID的这一项，返回出来newAtt

//所有场馆的数据
export const allData = [
  {
    id: '101',
    game_type: '1',
    name: 'EVO真人',
    rate: '9',
    en_name: 'EVO Casino',
    pt_name: 'EVO Casino',
    th_name: 'EVO Casino',
    vn_name: 'EVO Casino',
    zh_name: 'EVO真人',
  },
  {
    id: '301',
    game_type: '3',
    name: 'PG电子',
    rate: '13',
    en_name: 'Slot PG',
    pt_name: 'Slot PG',
    th_name: 'Slot PG',
    vn_name: 'Slot PG',
    zh_name: 'PG电子',
  },
  {
    id: '302',
    game_type: '3',
    name: 'EVO电子',
    rate: '13',
    en_name: 'Slot EVO',
    pt_name: 'Slot EVO',
    th_name: 'Slot EVO',
    vn_name: 'Slot EVO',
    zh_name: 'EVO电子',
  },
];

//编辑场馆数据
export const editData = [
  {
    id: '101',
    game_type: '1',
    name: 'EVO真人',
    rate: '',
    en_name: 'EVO Casino',
    pt_name: 'EVO Casino',
    th_name: 'EVO Casino',
    vn_name: 'EVO Casino',
    zh_name: 'EVO真人',
  },
  {
    id: '102',
    game_type: '1',
    name: 'PP真人',
    rate: '',
    en_name: 'PP Casino',
    pt_name: 'PP Casino',
    th_name: 'PP Casino',
    vn_name: 'PP Casino',
    zh_name: 'PP真人',
  },
  {
    id: '301',
    game_type: '3',
    name: 'PG电子',
    rate: '',
    en_name: 'Slot PG',
    pt_name: 'Slot PG',
    th_name: 'Slot PG',
    vn_name: 'Slot PG',
    zh_name: 'PG电子',
  },
  {
    id: '302',
    game_type: '3',
    name: 'EVO电子',
    rate: '',
    en_name: 'Slot EVO',
    pt_name: 'Slot EVO',
    th_name: 'Slot EVO',
    vn_name: 'Slot EVO',
    zh_name: 'EVO电子',
  },
  {
    id: '303',
    game_type: '3',
    name: 'PP电子',
    rate: '',
    en_name: 'Slot PP',
    pt_name: 'Slot PP',
    th_name: 'Slot PP',
    vn_name: 'Slot PP',
    zh_name: 'PP电子',
  },
  {
    id: '401',
    game_type: '4',
    name: 'IM体育',
    rate: '',
    en_name: 'IM Sport',
    pt_name: 'IM Sport',
    th_name: 'IM Sport',
    vn_name: 'IM Sport',
    zh_name: 'IM体育',
  },
];

//如果allData为[],返回新数组的值是以editData为主，如果allData有值，allData数组里边的rate值要赋给editData的data值

const object = {
  t1rate: '1.00',
  t2rate: '1.00',
  t3rate: '1.00',
  t4rate: '2',
};

const array = [
  {
    game_type: 1,
  },
  {
    game_type: 2,
  },
  {
    game_type: 3,
  },
  {
    game_type: 4,
  },
];

// object 和array  变成newArrry

const newArrry = [
  {
    game_type: 1,
    rate: '1.00',
  },
  {
    game_type: 2,
    rate: '1.00',
  },
  {
    game_type: 3,
    rate: '1.00',
  },
  {
    game_type: 4,
    rate: '2',
  },
];

const currently = [
  {
    id: '101',
    game_type: '1',
    name: 'Evolution',
    rate: '3',
    en_name: 'Evolution Casino',
    pt_name: 'Evolution Casino',
    th_name: 'Evolution Casino',
    vn_name: 'Evolution Casino',
    zh_name: 'Evolution视讯',
  },
  {
    id: '102',
    game_type: '1',
    name: 'Pragmatic Play',
    currency_id: ['732'],
    rate: '8',
    en_name: 'Pragmatic Play Casino',
    pt_name: 'Pragmatic Play Casino',
    th_name: 'Pragmatic Play Casino',
    vn_name: 'Pragmatic Play Casino',
    zh_name: 'Pragmatic Play视讯',
  },
  {
    id: '201',
    game_type: '2',
    name: 'JUST DO THE BEST',
    rate: '8',
    en_name: 'JUST DO THE BEST Slot',
    pt_name: 'JUST DO THE BEST Slot',
    th_name: 'JUST DO THE BEST Slot',
    vn_name: 'JUST DO THE BEST Slot',
    zh_name: 'JUST DO THE BEST捕鱼',
  },
  {
    id: '301',
    game_type: '3',
    name: 'PG Soft',
    rate: '0',
    en_name: 'PG Soft Slot',
    pt_name: 'PG Soft Slot',
    th_name: 'PG Soft Slot',
    vn_name: 'PG Soft Slot',
    zh_name: 'PG Soft老虎机',
  },
  {
    id: '303',
    game_type: '3',
    name: 'Pragmatic Play',
    rate: '0',
    en_name: 'Pragmatic Play Slot',
    pt_name: 'Pragmatic Play Slot',
    th_name: 'Pragmatic Play Slot',
    vn_name: 'Pragmatic Play Slot',
    zh_name: 'Pragmatic Play老虎机',
  },
  {
    id: '304',
    game_type: '3',
    name: 'Big Time Gaming',
    rate: '0',
    en_name: 'Big Time Gaming Slot',
    pt_name: 'Big Time Gaming Slot',
    th_name: 'Big Time Gaming Slot',
    vn_name: 'Big Time Gaming Slot',
    zh_name: 'Big Time Gaming老虎机',
  },
  {
    id: '305',
    game_type: '3',
    name: 'Netent',
    rate: '0',
    en_name: 'Netent Slot',
    pt_name: 'Netent Slot',
    th_name: 'Netent Slot',
    vn_name: 'Netent Slot',
    zh_name: 'Netent老虎机',
  },
  {
    id: '306',
    game_type: '3',
    name: 'Nolimit City',
    rate: '0',
    en_name: 'Nolimit City Slot',
    pt_name: 'Nolimit City\n Slot',
    th_name: 'Nolimit City\n Slot',
    vn_name: 'Nolimit City\n Slot',
    zh_name: 'Nolimit City\n老虎机',
  },
  {
    id: '307',
    game_type: '3',
    name: 'Red Tiger',
    rate: '0',
    en_name: 'Red Tiger Slot',
    pt_name: 'Red Tiger Slot',
    th_name: 'Red Tiger Slot',
    vn_name: 'Red Tiger Slot',
    zh_name: 'Red Tiger老虎机',
  },
  {
    id: '308',
    game_type: '3',
    name: 'JUST DO THE BEST',
    rate: '0',
    en_name: 'JUST DO THE BEST Slot',
    pt_name: 'JUST DO THE BEST Slot',
    th_name: 'JUST DO THE BEST Slot',
    vn_name: 'JUST DO THE BEST Slot',
    zh_name: 'JUST DO THE BEST老虎机',
  },
  {
    id: '401',
    game_type: '4',
    name: 'Inplay Matrix',
    rate: '0',
    en_name: 'Inplay Matrix Sport',
    pt_name: 'Inplay Matrix Sport',
    th_name: 'Inplay Matrix Sport',
    vn_name: 'Inplay Matrix Sport',
    zh_name: 'Inplay Matrix体育',
  },
];
const bizhong = [
  {
    id: '101',
    game_type: '1',
    currency_id: '701',
    rate: '3',
  },
  {
    id: '101',
    game_type: '1',
    currency_id: '702',
    rate: '3',
  },
];
const newCurrently = [
  {
    id: '101',
    game_type: '1',
    name: 'Evolution',
    rate: '3',
    en_name: 'Evolution Casino',
    pt_name: 'Evolution Casino',
    th_name: 'Evolution Casino',
    vn_name: 'Evolution Casino',
    zh_name: 'Evolution视讯',
  },
  {
    id: '101',
    game_type: '1',
    name: 'Evolution',
    rate: '3',
    currency_id: '701',
    en_name: 'Evolution Casino',
    pt_name: 'Evolution Casino',
    th_name: 'Evolution Casino',
    vn_name: 'Evolution Casino',
    zh_name: 'Evolution视讯',
  },
  {
    id: '101',
    game_type: '1',
    name: 'Evolution',
    rate: '3',
    currency_id: '702',
    en_name: 'Evolution Casino',
    pt_name: 'Evolution Casino',
    th_name: 'Evolution Casino',
    vn_name: 'Evolution Casino',
    zh_name: 'Evolution视讯',
  },
  {
    id: '102',
    game_type: '1',
    name: 'Pragmatic Play',
    rate: '8',
    en_name: 'Pragmatic Play Casino',
    pt_name: 'Pragmatic Play Casino',
    th_name: 'Pragmatic Play Casino',
    vn_name: 'Pragmatic Play Casino',
    zh_name: 'Pragmatic Play视讯',
  },
  {
    id: '102',
    game_type: '1',
    currency_id: '701',
    rate: '3',
    en_name: 'Pragmatic Play Casino',
    pt_name: 'Pragmatic Play Casino',
    th_name: 'Pragmatic Play Casino',
    vn_name: 'Pragmatic Play Casino',
    zh_name: 'Pragmatic Play视讯',
  },
  {
    id: '102',
    game_type: '1',
    currency_id: '702',
    rate: '3',
    en_name: 'Pragmatic Play Casino',
    pt_name: 'Pragmatic Play Casino',
    th_name: 'Pragmatic Play Casino',
    vn_name: 'Pragmatic Play Casino',
    zh_name: 'Pragmatic Play视讯',
  },
  {
    id: '201',
    game_type: '2',
    name: 'JUST DO THE BEST',
    rate: '8',
    en_name: 'JUST DO THE BEST Slot',
    pt_name: 'JUST DO THE BEST Slot',
    th_name: 'JUST DO THE BEST Slot',
    vn_name: 'JUST DO THE BEST Slot',
    zh_name: 'JUST DO THE BEST捕鱼',
  },
  {
    id: '201',
    game_type: '1',
    name: 'JUST DO THE BEST',
    currency_id: '701',
    rate: '3',
    en_name: 'JUST DO THE BEST Slot',
    pt_name: 'JUST DO THE BEST Slot',
    th_name: 'JUST DO THE BEST Slot',
    vn_name: 'JUST DO THE BEST Slot',
    zh_name: 'JUST DO THE BEST捕鱼',
  },
  {
    id: '201',
    game_type: '1',
    name: 'JUST DO THE BEST',
    currency_id: '702',
    rate: '3',
    en_name: 'JUST DO THE BEST Slot',
    pt_name: 'JUST DO THE BEST Slot',
    th_name: 'JUST DO THE BEST Slot',
    vn_name: 'JUST DO THE BEST Slot',
    zh_name: 'JUST DO THE BEST捕鱼',
  },
  {
    id: '301',
    game_type: '3',
    name: 'PG Soft',
    rate: '0',
    en_name: 'PG Soft Slot',
    pt_name: 'PG Soft Slot',
    th_name: 'PG Soft Slot',
    vn_name: 'PG Soft Slot',
    zh_name: 'PG Soft老虎机',
  },
  {
    id: '301',
    game_type: '3',
    name: 'PG Soft',
    currency_id: '701',
    rate: '3',
    en_name: 'PG Soft Slot',
    pt_name: 'PG Soft Slot',
    th_name: 'PG Soft Slot',
    vn_name: 'PG Soft Slot',
    zh_name: 'PG Soft老虎机',
  },
  {
    id: '301',
    game_type: '1',
    name: 'PG Soft',
    currency_id: '702',
    rate: '3',
    en_name: 'PG Soft Slot',
    pt_name: 'PG Soft Slot',
    th_name: 'PG Soft Slot',
    vn_name: 'PG Soft Slot',
    zh_name: 'PG Soft老虎机',
  },
  {
    id: '303',
    game_type: '3',
    name: 'Pragmatic Play',
    rate: '0',
    en_name: 'Pragmatic Play Slot',
    pt_name: 'Pragmatic Play Slot',
    th_name: 'Pragmatic Play Slot',
    vn_name: 'Pragmatic Play Slot',
    zh_name: 'Pragmatic Play老虎机',
  },
  {
    id: '303',
    game_type: '3',
    name: 'Pragmatic Play',
    currency_id: '701',
    rate: '3',
    en_name: 'Pragmatic Play Slot',
    pt_name: 'Pragmatic Play Slot',
    th_name: 'Pragmatic Play Slot',
    vn_name: 'Pragmatic Play Slot',
    zh_name: 'Pragmatic Play老虎机',
  },
  {
    id: '303',
    game_type: '3',
    name: 'Pragmatic Play',
    currency_id: '702',
    rate: '3',
    en_name: 'Pragmatic Play Slot',
    pt_name: 'Pragmatic Play Slot',
    th_name: 'Pragmatic Play Slot',
    vn_name: 'Pragmatic Play Slot',
    zh_name: 'Pragmatic Play老虎机',
  },
  {
    id: '304',
    game_type: '3',
    name: 'Big Time Gaming',
    rate: '0',
    en_name: 'Big Time Gaming Slot',
    pt_name: 'Big Time Gaming Slot',
    th_name: 'Big Time Gaming Slot',
    vn_name: 'Big Time Gaming Slot',
    zh_name: 'Big Time Gaming老虎机',
  },
  {
    id: '304',
    game_type: '3',
    name: 'Big Time Gaming',
    currency_id: '701',
    rate: '3',
    en_name: 'Big Time Gaming Slot',
    pt_name: 'Big Time Gaming Slot',
    th_name: 'Big Time Gaming Slot',
    vn_name: 'Big Time Gaming Slot',
    zh_name: 'Big Time Gaming老虎机',
  },
  {
    id: '304',
    game_type: '3',
    name: 'Big Time Gaming',
    currency_id: '702',
    rate: '3',
    en_name: 'Big Time Gaming Slot',
    pt_name: 'Big Time Gaming Slot',
    th_name: 'Big Time Gaming Slot',
    vn_name: 'Big Time Gaming Slot',
    zh_name: 'Big Time Gaming老虎机',
  },
  {
    id: '305',
    game_type: '3',
    name: 'Netent',
    rate: '0',
    en_name: 'Big Time Gaming Slot',
    pt_name: 'Big Time Gaming Slot',
    th_name: 'Big Time Gaming Slot',
    vn_name: 'Big Time Gaming Slot',
    zh_name: 'Big Time Gaming老虎机',
  },
  {
    id: '305',
    game_type: '3',
    name: 'Netent',
    currency_id: '701',
    rate: '3',
    en_name: 'Big Time Gaming Slot',
    pt_name: 'Big Time Gaming Slot',
    th_name: 'Big Time Gaming Slot',
    vn_name: 'Big Time Gaming Slot',
    zh_name: 'Big Time Gaming老虎机',
  },
  {
    id: '305',
    game_type: '3',
    name: 'Netent',
    currency_id: '702',
    rate: '3',
    en_name: 'Big Time Gaming Slot',
    pt_name: 'Big Time Gaming Slot',
    th_name: 'Big Time Gaming Slot',
    vn_name: 'Big Time Gaming Slot',
    zh_name: 'Big Time Gaming老虎机',
  },
  {
    id: '306',
    game_type: '3',
    name: 'Nolimit City',
    rate: '3',
    en_name: 'Nolimit City Slot',
    pt_name: 'Nolimit City\n Slot',
    th_name: 'Nolimit City\n Slot',
    vn_name: 'Nolimit City\n Slot',
    zh_name: 'Nolimit City\n老虎机',
  },
  {
    id: '306',
    game_type: '3',
    name: 'Nolimit City',
    currency_id: '701',
    rate: '3',
    en_name: 'Nolimit City Slot',
    pt_name: 'Nolimit City\n Slot',
    th_name: 'Nolimit City\n Slot',
    vn_name: 'Nolimit City\n Slot',
    zh_name: 'Nolimit City\n老虎机',
  },
  {
    id: '306',
    game_type: '3',
    name: 'Nolimit City',
    currency_id: '702',
    rate: '3',
    en_name: 'Nolimit City Slot',
    pt_name: 'Nolimit City\n Slot',
    th_name: 'Nolimit City\n Slot',
    vn_name: 'Nolimit City\n Slot',
    zh_name: 'Nolimit City\n老虎机',
  },
  {
    id: '307',
    game_type: '3',
    name: 'Red Tiger',
    rate: '0',
    en_name: 'Red Tiger Slot',
    pt_name: 'Red Tiger Slot',
    th_name: 'Red Tiger Slot',
    vn_name: 'Red Tiger Slot',
    zh_name: 'Red Tiger老虎机',
  },
  {
    id: '307',
    game_type: '3',
    name: 'Red Tiger',
    currency_id: '701',
    rate: '3',
    en_name: 'Red Tiger Slot',
    pt_name: 'Red Tiger Slot',
    th_name: 'Red Tiger Slot',
    vn_name: 'Red Tiger Slot',
    zh_name: 'Red Tiger老虎机',
  },
  {
    id: '307',
    game_type: '3',
    name: 'Red Tiger',
    currency_id: '702',
    rate: '3',
    en_name: 'Red Tiger Slot',
    pt_name: 'Red Tiger Slot',
    th_name: 'Red Tiger Slot',
    vn_name: 'Red Tiger Slot',
    zh_name: 'Red Tiger老虎机',
  },
  {
    id: '308',
    game_type: '3',
    name: 'JUST DO THE BEST',
    rate: '0',
    en_name: 'JUST DO THE BEST Slot',
    pt_name: 'JUST DO THE BEST Slot',
    th_name: 'JUST DO THE BEST Slot',
    vn_name: 'JUST DO THE BEST Slot',
    zh_name: 'JUST DO THE BEST老虎机',
  },
  {
    id: '307',
    game_type: '3',
    name: 'JUST DO THE BEST',
    currency_id: '701',
    rate: '3',
    en_name: 'JUST DO THE BEST Slot',
    pt_name: 'JUST DO THE BEST Slot',
    th_name: 'JUST DO THE BEST Slot',
    vn_name: 'JUST DO THE BEST Slot',
    zh_name: 'JUST DO THE BEST老虎机',
  },
  {
    id: '307',
    game_type: '3',
    name: 'JUST DO THE BEST',
    currency_id: '702',
    rate: '3',
    en_name: 'JUST DO THE BEST Slot',
    pt_name: 'JUST DO THE BEST Slot',
    th_name: 'JUST DO THE BEST Slot',
    vn_name: 'JUST DO THE BEST Slot',
    zh_name: 'JUST DO THE BEST老虎机',
  },
  {
    id: '401',
    game_type: '4',
    name: 'Inplay Matrix',
    rate: '0',
    en_name: 'Inplay Matrix Sport',
    pt_name: 'Inplay Matrix Sport',
    th_name: 'Inplay Matrix Sport',
    vn_name: 'Inplay Matrix Sport',
    zh_name: 'Inplay Matrix体育',
  },
  {
    id: '401',
    game_type: '3',
    name: 'Inplay Matrix',
    currency_id: '701',
    rate: '3',
    en_name: 'Inplay Matrix Sport',
    pt_name: 'Inplay Matrix Sport',
    th_name: 'Inplay Matrix Sport',
    vn_name: 'Inplay Matrix Sport',
    zh_name: 'Inplay Matrix体育',
  },
  {
    id: '401',
    game_type: '3',
    name: 'Inplay Matrix',
    currency_id: '702',
    rate: '3',
    en_name: 'Inplay Matrix Sport',
    pt_name: 'Inplay Matrix Sport',
    th_name: 'Inplay Matrix Sport',
    vn_name: 'Inplay Matrix Sport',
    zh_name: 'Inplay Matrix体育',
  },
];
