import { BasicColumn } from '/@/components/Table';
import { useI18n } from '/@/hooks/web/useI18n';

const { t } = useI18n();
export const columns: BasicColumn[] = [
  {
    title: t('business.commin_vip_level'),
    dataIndex: 'name',
  },
  {
    title: t('common.IMSports'),
    dataIndex: 'address',
  },
  {
    title: t('common.agRealPerson'),
    dataIndex: 'agGame',
  },
  {
    title: t('common.PGElectronics'),
    dataIndex: 'pgGame',
  },
];

export const testData = [
  {
    vipName: t('business.commin_vip_level'),
    game1: t('common.evoRealPerson'),
    game2: t('common.IMSports'),
    game3: t('common.ABSports'),
    game4: t('common.CDSports'),
    game5: t('common.EFSports'),
    game6: t('common.EVOElectronics'),
    game7: t('common.PGElectronics'),
  },
  {
    vipName: 'VIP0',
    game1: '78',
    game2: '4',
    game3: '4',
    game4: '4',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP1',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP2',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP3',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP4',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP4',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP6',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP7',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP8',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP9',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP10',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
];

//这是个js数组，使用js将testData[0]组成表头，比如这个形式
// export const columns: BasicColumn[] = [
//   {
//     title: 'VIP等级',
//     dataIndex: 'vipName',
//   },
//   {
//     title: 'EVO真人',
//     dataIndex: 'game1',
//   },
//   {
//     title: 'IM体育',
//     dataIndex: 'game2',
//   },
//   {
//     title: t('common.ABSports'),
//     dataIndex: 'game2',
//   },
//   {
//     title: t('common.CDSports'),
//     dataIndex: 'game3',
//   },
//   {
//     title: t('common.EFSports'),
//     dataIndex: 'game4',
//   }
//   {
//     title: t('common.EVOElectronics'),
//     dataIndex: 'game5',
//   }
//   {
//     title: 'PG电子',
//     dataIndex: 'game6',
//   }
// ];

export const getData = [
  {
    game_type: '1',
    data: [
      {
        id: '101',
        en_name: 'EVO Casino',
        game_type: '1',
        zh_name: 'EVO真人',
        pt_name: 'EVO Casino',
        vn_name: 'EVO Casino',
        th_name: 'EVO Casino',
        name: 'EVO真人',
        rate: '0.00',
      },
    ],
  },
  {
    game_type: '4',
    data: [
      {
        id: '401',
        en_name: 'IM Sport',
        game_type: '4',
        zh_name: 'IM体育',
        pt_name: 'IM Sport',
        vn_name: 'IM Sport',
        th_name: 'IM Sport',
        name: 'IM体育',
        rate: '0.00',
      },
      {
        id: '412',
        en_name: 'AB Sport',
        game_type: '4',
        zh_name: 'AB体育',
        pt_name: 'AB Sport',
        vn_name: 'AB Sport',
        th_name: 'AB Sport',
        name: 'AB体育',
        rate: '0.00',
      },
      {
        id: '422',
        en_name: 'CD Sport',
        game_type: '4',
        zh_name: 'CD体育',
        pt_name: 'CD Sport',
        vn_name: 'CD Sport',
        th_name: 'CD Sport',
        name: 'CD体育',
        rate: '0.00',
      },
      {
        id: '432',
        en_name: 'EF Sport',
        game_type: '4',
        zh_name: 'EF体育',
        pt_name: 'EF Sport',
        vn_name: 'EF Sport',
        th_name: 'EF Sport',
        name: 'EF体育',
        rate: '0.00',
      },
    ],
  },
  {
    game_type: '3',
    data: [
      {
        id: '302',
        en_name: 'Slot EVO',
        game_type: '3',
        zh_name: 'EVO电子',
        pt_name: 'Slot EVO',
        vn_name: 'Slot EVO',
        th_name: 'Slot EVO',
        name: 'EVO电子',
        rate: '0.00',
      },
      {
        id: '301',
        en_name: 'Slot PG',
        game_type: '3',
        zh_name: 'PG电子',
        pt_name: 'Slot PG',
        vn_name: 'Slot PG',
        th_name: 'Slot PG',
        name: 'PG电子',
        rate: '0.00',
      },
    ],
  },
];

export const object = {
  vipName: t('business.commin_vip_level'),
  game1: t('common.evoRealPerson'),
  game2: t('common.IMSports'),
  game3: t('common.ABSports'),
  game4: t('common.CDSports'),
  game5: t('common.EFSports'),
  game6: t('common.EVOElectronics'),
  game7: t('common.PGElectronics'),
};

export const ossUrlarr = [
  {
    game_type: '1',
    data: [
      {
        id: '101',
        en_name: 'EVO Casino',
        game_type: '1',
        zh_name: 'EVO真人',
        pt_name: 'EVO Casino',
        vn_name: 'EVO Casino',
        th_name: 'EVO Casino',
        name: 'EVO真人',
        rate: '0.00',
      },
    ],
  },
  {
    game_type: '4',
    data: [
      {
        id: '401',
        en_name: 'IM Sport',
        game_type: '4',
        zh_name: 'IM体育',
        pt_name: 'IM Sport',
        vn_name: 'IM Sport',
        th_name: 'IM Sport',
        name: 'IM体育',
        rate: '0.00',
      },
      {
        id: '412',
        en_name: 'AB Sport',
        game_type: '4',
        zh_name: 'AB体育',
        pt_name: 'AB Sport',
        vn_name: 'AB Sport',
        th_name: 'AB Sport',
        name: 'AB体育',
        rate: '0.00',
      },
      {
        id: '422',
        en_name: 'CD Sport',
        game_type: '4',
        zh_name: 'CD体育',
        pt_name: 'CD Sport',
        vn_name: 'CD Sport',
        th_name: 'CD Sport',
        name: 'CD体育',
        rate: '0.00',
      },
      {
        id: '432',
        en_name: 'EF Sport',
        game_type: '4',
        zh_name: 'EF体育',
        pt_name: 'EF Sport',
        vn_name: 'EF Sport',
        th_name: 'EF Sport',
        name: 'EF体育',
        rate: '0.00',
      },
    ],
  },
  {
    game_type: '3',
    data: [
      {
        id: '302',
        en_name: 'Slot EVO',
        game_type: '3',
        zh_name: 'EVO电子',
        pt_name: 'Slot EVO',
        vn_name: 'Slot EVO',
        th_name: 'Slot EVO',
        name: 'EVO电子',
        rate: '0.00',
      },
      {
        id: '301',
        en_name: 'Slot PG',
        game_type: '3',
        zh_name: 'PG电子',
        pt_name: 'Slot PG',
        vn_name: 'Slot PG',
        th_name: 'Slot PG',
        name: 'PG电子',
        rate: '0.00',
      },
    ],
  },
];

//js将ossUrlarr数组变成ossUrlarrNew

const arrHeader = [t('common.EVOElectronics'), t('common.PGElectronics'), t('common.evoRealPerson'), t('common.IMSports'), t('common.ABSports'), t('common.CDSports'), t('common.EFSports')];
const headerObject = {
  vipName: t('business.commin_vip_level'),
  game1: t('common.evoRealPerson'),
  game2: t('common.IMSports'),
  game3: t('common.ABSports'),
  game4: t('common.CDSports'),
  game5: t('common.EFSports'),
  game6: t('common.EVOElectronics'),
  game7: t('common.PGElectronics'),
};

//js将arrHeader变成headerObject

const content = [
  {
    level: '4',
    alias: '铜',
    member_count: 0,
    score: '1000.00',
    up_gift: '45.00',
    daily_gift: '8.00',
    weekly_gift: '28.00',
    monthly_gift: '88.00',
    is_default: 2,
    rebate_config: [],
    created_at: 1696582334,
    updated_at: 1700131392,
  },
  {
    level: '7',
    alias: '钻石',
    member_count: 0,
    score: '2.00',
    up_gift: '45.00',
    daily_gift: '2.00',
    weekly_gift: '2.00',
    monthly_gift: '2.00',
    is_default: 2,
    rebate_config: [
      {
        game_type: '4',
        data: [
          {
            id: '401',
            en_name: 'IM Sport',
            game_type: '4',
            zh_name: 'IM体育',
            pt_name: 'IM Sport',
            vn_name: 'IM Sport',
            th_name: 'IM Sport',
            name: 'IM体育',
            rate: '45',
          },
          {
            id: '412',
            en_name: 'AB Sport',
            game_type: '4',
            zh_name: 'AB体育',
            pt_name: 'AB Sport',
            vn_name: 'AB Sport',
            th_name: 'AB Sport',
            name: 'AB体育',
            rate: '0.00',
          },
          {
            id: '422',
            en_name: 'CD Sport',
            game_type: '4',
            zh_name: 'CD体育',
            pt_name: 'CD Sport',
            vn_name: 'CD Sport',
            th_name: 'CD Sport',
            name: 'CD体育',
            rate: '0.00',
          },
          {
            id: '432',
            en_name: 'EF Sport',
            game_type: '4',
            zh_name: 'EF体育',
            pt_name: 'EF Sport',
            vn_name: 'EF Sport',
            th_name: 'EF Sport',
            name: 'EF体育',
            rate: '0.00',
          },
        ],
      },
      {
        game_type: '3',
        data: [
          {
            id: '302',
            en_name: 'Slot EVO',
            game_type: '3',
            zh_name: 'EVO电子',
            pt_name: 'Slot EVO',
            vn_name: 'Slot EVO',
            th_name: 'Slot EVO',
            name: 'EVO电子',
            rate: '0.00',
          },
          {
            id: '301',
            en_name: 'Slot PG',
            game_type: '3',
            zh_name: 'PG电子',
            pt_name: 'Slot PG',
            vn_name: 'Slot PG',
            th_name: 'Slot PG',
            name: 'PG电子',
            rate: '0.00',
          },
        ],
      },
      {
        game_type: '1',
        data: [
          {
            id: '101',
            en_name: 'EVO Casino',
            game_type: '1',
            zh_name: 'EVO真人',
            pt_name: 'EVO Casino',
            vn_name: 'EVO Casino',
            th_name: 'EVO Casino',
            name: 'EVO真人',
            rate: '0.00',
          },
        ],
      },
    ],
    created_at: 1695954504,
    updated_at: 1700134114,
  },
  {
    level: '8',
    alias: '钻石',
    member_count: 0,
    score: '2.00',
    up_gift: '2.00',
    daily_gift: '2.00',
    weekly_gift: '2.00',
    monthly_gift: '2.00',
    is_default: 2,
    rebate_config: [],
    created_at: 1695954504,
    updated_at: 1697008124,
  },
  {
    level: '9',
    alias: '钻石',
    member_count: 0,
    score: '2.00',
    up_gift: '2.00',
    daily_gift: '2.00',
    weekly_gift: '2.00',
    monthly_gift: '89.00',
    is_default: 2,
    rebate_config: [
      {
        game_type: '1',
        data: [
          {
            id: '101',
            en_name: 'EVO Casino',
            game_type: '1',
            zh_name: 'EVO真人',
            pt_name: 'EVO Casino',
            vn_name: 'EVO Casino',
            th_name: 'EVO Casino',
            name: 'EVO真人',
            rate: '78',
          },
        ],
      },
      {
        game_type: '4',
        data: [
          {
            id: '401',
            en_name: 'IM Sport',
            game_type: '4',
            zh_name: 'IM体育',
            pt_name: 'IM Sport',
            vn_name: 'IM Sport',
            th_name: 'IM Sport',
            name: 'IM体育',
            rate: '8',
          },
          {
            id: '412',
            en_name: 'AB Sport',
            game_type: '4',
            zh_name: 'AB体育',
            pt_name: 'AB Sport',
            vn_name: 'AB Sport',
            th_name: 'AB Sport',
            name: 'AB体育',
            rate: '9',
          },
          {
            id: '422',
            en_name: 'CD Sport',
            game_type: '4',
            zh_name: 'CD体育',
            pt_name: 'CD Sport',
            vn_name: 'CD Sport',
            th_name: 'CD Sport',
            name: 'CD体育',
            rate: '36',
          },
          {
            id: '432',
            en_name: 'EF Sport',
            game_type: '4',
            zh_name: 'EF体育',
            pt_name: 'EF Sport',
            vn_name: 'EF Sport',
            th_name: 'EF Sport',
            name: 'EF体育',
            rate: '1',
          },
        ],
      },
      {
        game_type: '3',
        data: [
          {
            id: '302',
            en_name: 'Slot EVO',
            game_type: '3',
            zh_name: 'EVO电子',
            pt_name: 'Slot EVO',
            vn_name: 'Slot EVO',
            th_name: 'Slot EVO',
            name: 'EVO电子',
            rate: '1',
          },
          {
            id: '301',
            en_name: 'Slot PG',
            game_type: '3',
            zh_name: 'PG电子',
            pt_name: 'Slot PG',
            vn_name: 'Slot PG',
            th_name: 'Slot PG',
            name: 'PG电子',
            rate: '12',
          },
        ],
      },
    ],
    created_at: 1695954504,
    updated_at: 1700133969,
  },
  {
    level: '10',
    alias: '钻石',
    member_count: 0,
    score: '45.00',
    up_gift: '2.00',
    daily_gift: '2.00',
    weekly_gift: '2.00',
    monthly_gift: '2.00',
    is_default: 2,
    rebate_config: [],
    created_at: 1695954504,
    updated_at: 1700117702,
  },
  {
    level: '0',
    alias: '金',
    member_count: 0,
    score: '20000.00',
    up_gift: '45.00',
    daily_gift: '8.00',
    weekly_gift: '28.00',
    monthly_gift: '88.00',
    is_default: 1,
    rebate_config: [
      {
        game_type: '1',
        data: [
          {
            id: '101',
            en_name: 'EVO Casino',
            game_type: '1',
            zh_name: 'EVO真人',
            pt_name: 'EVO Casino',
            vn_name: 'EVO Casino',
            th_name: 'EVO Casino',
            name: 'EVO真人',
            rate: '78',
          },
        ],
      },
      {
        game_type: '4',
        data: [
          {
            id: '401',
            en_name: 'IM Sport',
            game_type: '4',
            zh_name: 'IM体育',
            pt_name: 'IM Sport',
            vn_name: 'IM Sport',
            th_name: 'IM Sport',
            name: 'IM体育',
            rate: '8',
          },
          {
            id: '412',
            en_name: 'AB Sport',
            game_type: '4',
            zh_name: 'AB体育',
            pt_name: 'AB Sport',
            vn_name: 'AB Sport',
            th_name: 'AB Sport',
            name: 'AB体育',
            rate: '2',
          },
          {
            id: '422',
            en_name: 'CD Sport',
            game_type: '4',
            zh_name: 'CD体育',
            pt_name: 'CD Sport',
            vn_name: 'CD Sport',
            th_name: 'CD Sport',
            name: 'CD体育',
            rate: '7',
          },
          {
            id: '432',
            en_name: 'EF Sport',
            game_type: '4',
            zh_name: 'EF体育',
            pt_name: 'EF Sport',
            vn_name: 'EF Sport',
            th_name: 'EF Sport',
            name: 'EF体育',
            rate: '8',
          },
        ],
      },
      {
        game_type: '3',
        data: [
          {
            id: '302',
            en_name: 'Slot EVO',
            game_type: '3',
            zh_name: 'EVO电子',
            pt_name: 'Slot EVO',
            vn_name: 'Slot EVO',
            th_name: 'Slot EVO',
            name: 'EVO电子',
            rate: '0.00',
          },
          {
            id: '301',
            en_name: 'Slot PG',
            game_type: '3',
            zh_name: 'PG电子',
            pt_name: 'Slot PG',
            vn_name: 'Slot PG',
            th_name: 'Slot PG',
            name: 'PG电子',
            rate: '0.00',
          },
        ],
      },
    ],
    created_at: 1696475183,
    updated_at: 1700135924,
  },
  {
    level: '1',
    alias: '铜',
    member_count: 0,
    score: '1000.00',
    up_gift: '45.00',
    daily_gift: '8.00',
    weekly_gift: '28.00',
    monthly_gift: '88.00',
    is_default: 2,
    rebate_config: [
      {
        game_type: '1',
        data: [
          {
            id: '101',
            en_name: 'EVO Casino',
            game_type: '1',
            zh_name: 'EVO真人',
            pt_name: 'EVO Casino',
            vn_name: 'EVO Casino',
            th_name: 'EVO Casino',
            name: 'EVO真人',
            rate: '7',
          },
        ],
      },
      {
        game_type: '4',
        data: [
          {
            id: '401',
            en_name: 'IM Sport',
            game_type: '4',
            zh_name: 'IM体育',
            pt_name: 'IM Sport',
            vn_name: 'IM Sport',
            th_name: 'IM Sport',
            name: 'IM体育',
            rate: '45',
          },
          {
            id: '412',
            en_name: 'AB Sport',
            game_type: '4',
            zh_name: 'AB体育',
            pt_name: 'AB Sport',
            vn_name: 'AB Sport',
            th_name: 'AB Sport',
            name: 'AB体育',
            rate: '5',
          },
          {
            id: '422',
            en_name: 'CD Sport',
            game_type: '4',
            zh_name: 'CD体育',
            pt_name: 'CD Sport',
            vn_name: 'CD Sport',
            th_name: 'CD Sport',
            name: 'CD体育',
            rate: '3',
          },
          {
            id: '432',
            en_name: 'EF Sport',
            game_type: '4',
            zh_name: 'EF体育',
            pt_name: 'EF Sport',
            vn_name: 'EF Sport',
            th_name: 'EF Sport',
            name: 'EF体育',
            rate: '1',
          },
        ],
      },
      {
        game_type: '3',
        data: [
          {
            id: '302',
            en_name: 'Slot EVO',
            game_type: '3',
            zh_name: 'EVO电子',
            pt_name: 'Slot EVO',
            vn_name: 'Slot EVO',
            th_name: 'Slot EVO',
            name: 'EVO电子',
            rate: '8',
          },
          {
            id: '301',
            en_name: 'Slot PG',
            game_type: '3',
            zh_name: 'PG电子',
            pt_name: 'Slot PG',
            vn_name: 'Slot PG',
            th_name: 'Slot PG',
            name: 'PG电子',
            rate: '78',
          },
        ],
      },
    ],
    created_at: 1696475891,
    updated_at: 1700212339,
  },
  {
    level: '2',
    alias: '铜',
    member_count: 0,
    score: '1000.00',
    up_gift: '30.00',
    daily_gift: '8.00',
    weekly_gift: '28.00',
    monthly_gift: '88.00',
    is_default: 2,
    rebate_config: [],
    created_at: 1696490670,
    updated_at: 1700130853,
  },
  {
    level: '3',
    alias: '铜',
    member_count: 0,
    score: '1000.00',
    up_gift: '30.00',
    daily_gift: '8.00',
    weekly_gift: '28.00',
    monthly_gift: '88.00',
    is_default: 2,
    rebate_config: [
      {
        game_type: '1',
        data: [
          {
            id: '101',
            en_name: 'EVO Casino',
            game_type: '1',
            zh_name: 'EVO真人',
            pt_name: 'EVO Casino',
            vn_name: 'EVO Casino',
            th_name: 'EVO Casino',
            name: 'EVO真人',
            rate: '45',
          },
        ],
      },
      {
        game_type: '4',
        data: [
          {
            id: '401',
            en_name: 'IM Sport',
            game_type: '4',
            zh_name: 'IM体育',
            pt_name: 'IM Sport',
            vn_name: 'IM Sport',
            th_name: 'IM Sport',
            name: 'IM体育',
            rate: '0.00',
          },
          {
            id: '412',
            en_name: 'AB Sport',
            game_type: '4',
            zh_name: 'AB体育',
            pt_name: 'AB Sport',
            vn_name: 'AB Sport',
            th_name: 'AB Sport',
            name: 'AB体育',
            rate: '0.00',
          },
          {
            id: '422',
            en_name: 'CD Sport',
            game_type: '4',
            zh_name: 'CD体育',
            pt_name: 'CD Sport',
            vn_name: 'CD Sport',
            th_name: 'CD Sport',
            name: 'CD体育',
            rate: '0.00',
          },
          {
            id: '432',
            en_name: 'EF Sport',
            game_type: '4',
            zh_name: 'EF体育',
            pt_name: 'EF Sport',
            vn_name: 'EF Sport',
            th_name: 'EF Sport',
            name: 'EF体育',
            rate: '0.00',
          },
        ],
      },
      {
        game_type: '3',
        data: [
          {
            id: '302',
            en_name: 'Slot EVO',
            game_type: '3',
            zh_name: 'EVO电子',
            pt_name: 'Slot EVO',
            vn_name: 'Slot EVO',
            th_name: 'Slot EVO',
            name: 'EVO电子',
            rate: '0.00',
          },
          {
            id: '301',
            en_name: 'Slot PG',
            game_type: '3',
            zh_name: 'PG电子',
            pt_name: 'Slot PG',
            vn_name: 'Slot PG',
            th_name: 'Slot PG',
            name: 'PG电子',
            rate: '0.00',
          },
        ],
      },
    ],
    created_at: 1696490684,
    updated_at: 1700134127,
  },
  {
    level: '5',
    alias: '铜',
    member_count: 0,
    score: '1000.00',
    up_gift: '787878.00',
    daily_gift: '8.00',
    weekly_gift: '28.00',
    monthly_gift: '88.00',
    is_default: 2,
    rebate_config: [],
    created_at: 1696582342,
    updated_at: 1700117557,
  },
  {
    level: '6',
    alias: '铜',
    member_count: 0,
    score: '1000.00',
    up_gift: '30.00',
    daily_gift: '8.00',
    weekly_gift: '28.00',
    monthly_gift: '88.00',
    is_default: 2,
    rebate_config: [],
    created_at: 1696582521,
    updated_at: 1696907642,
  },
];
export const ossUrlarrNew = [
  {
    id: '101',
    en_name: 'EVO Casino',
    game_type: '1',
    zh_name: 'EVO真人',
    pt_name: 'EVO Casino',
    vn_name: 'EVO Casino',
    th_name: 'EVO Casino',
    name: 'EVO真人',
    rate: '0.00',
  },
  {
    id: '401',
    en_name: 'IM Sport',
    game_type: '4',
    zh_name: 'IM体育',
    pt_name: 'IM Sport',
    vn_name: 'IM Sport',
    th_name: 'IM Sport',
    name: 'IM体育',
    rate: '0.00',
  },
  {
    id: '412',
    en_name: 'AB Sport',
    game_type: '4',
    zh_name: 'AB体育',
    pt_name: 'AB Sport',
    vn_name: 'AB Sport',
    th_name: 'AB Sport',
    name: 'AB体育',
    rate: '0.00',
  },
  {
    id: '422',
    en_name: 'CD Sport',
    game_type: '4',
    zh_name: 'CD体育',
    pt_name: 'CD Sport',
    vn_name: 'CD Sport',
    th_name: 'CD Sport',
    name: 'CD体育',
    rate: '0.00',
  },
  {
    id: '432',
    en_name: 'EF Sport',
    game_type: '4',
    zh_name: 'EF体育',
    pt_name: 'EF Sport',
    vn_name: 'EF Sport',
    th_name: 'EF Sport',
    name: 'EF体育',
    rate: '0.00',
  },
  {
    id: '302',
    en_name: 'Slot EVO',
    game_type: '3',
    zh_name: 'EVO电子',
    pt_name: 'Slot EVO',
    vn_name: 'Slot EVO',
    th_name: 'Slot EVO',
    name: 'EVO电子',
    rate: '0.00',
  },
  {
    id: '301',
    en_name: 'Slot PG',
    game_type: '3',
    zh_name: 'PG电子',
    pt_name: 'Slot PG',
    vn_name: 'Slot PG',
    th_name: 'Slot PG',
    name: 'PG电子',
    rate: '0.00',
  },
];
//遍历content，如果rebate_config为空数组，ossUrlarrNew赋值给rebate_config

const details = [
  {
    level: '8',
    rebate_config: [
      {
        id: '101',
        name: t('common.evoRealPerson'),
        game_type: '4',
        rate: '0.00',
      },
      {
        id: '401',
        name: t('common.IMSports'),
        game_type: '4',
        rate: '0.00',
      },
      {
        id: '412',
        game_type: '4',
        name: t('common.ABSports'),
        rate: '0.00',
      },
      {
        id: '422',
        game_type: '4',
        name: t('common.CDSports'),
        rate: '0.00',
      },
      {
        id: '432',
        game_type: '4',
        name: t('common.EFSports'),
        rate: '0.00',
      },
      {
        id: '302',
        game_type: '3',
        name: t('common.EVOElectronics'),
        rate: '0.00',
      },
      {
        id: '301',
        game_type: '3',
        name: t('common.PGElectronics'),
        rate: '0.00',
      },
    ],
  },
  {
    level: '9',
    rebate_config: [
      {
        id: '101',
        game_type: '1',
        name: t('common.evoRealPerson'),
        rate: '78',
      },
      {
        id: '401',
        game_type: '4',
        name: t('common.IMSports'),
        rate: '8',
      },
      {
        id: '412',
        game_type: '4',
        name: t('common.ABSports'),
        rate: '9',
      },
      {
        id: '422',
        game_type: '4',
        name: t('common.CDSports'),
        rate: '36',
      },
      {
        id: '432',
        game_type: '4',
        name: t('common.EFSports'),
        rate: '1',
      },
      {
        id: '302',
        game_type: '3',
        name: t('common.EVOElectronics'),
        rate: '1',
      },
      {
        id: '301',
        game_type: '3',
        name: t('common.PGElectronics'),
        rate: '12',
      },
    ],
  },
  {
    level: '2',
    rebate_config: [
      {
        id: '101',
        game_type: '1',
        name: t('common.evoRealPerson'),
        rate: '0.00',
      },
      {
        id: '401',
        game_type: '4',
        name: t('common.IMSports'),
        rate: '0.00',
      },
      {
        id: '412',
        game_type: '4',
        name: t('common.ABSports'),
        rate: '0.00',
      },
      {
        id: '422',
        game_type: '4',
        name: t('common.CDSports'),
        rate: '0.00',
      },
      {
        id: '432',
        game_type: '4',
        name: t('common.EFSports'),
        rate: '0.00',
      },
      {
        id: '302',
        game_type: '3',
        name: t('common.EVOElectronics'),
        rate: '0.00',
      },
      {
        id: '301',
        game_type: '3',
        name: t('common.PGElectronics'),
        rate: '0.00',
      },
    ],
  },
  {
    level: '3',
    rebate_config: [
      {
        id: '101',
        game_type: '1',
        name: t('common.evoRealPerson'),
        rate: '45',
      },
      {
        id: '401',
        game_type: '4',
        name: t('common.IMSports'),
        rate: '0.00',
      },
      {
        id: '412',
        game_type: '4',
        name: t('common.ABSports'),
        rate: '0.00',
      },
      {
        id: '422',
        game_type: '4',
        name: t('common.CDSports'),
        rate: '0.00',
      },
      {
        id: '432',
        game_type: '4',
        name: t('common.EFSports'),
        rate: '0.00',
      },
      {
        id: '302',
        game_type: '3',
        name: t('common.EVOElectronics'),
        rate: '0.00',
      },
      {
        id: '301',
        game_type: '3',
        name: t('common.PGElectronics'),
        rate: '0.00',
      },
    ],
  },
  {
    level: '5',
    rebate_config: [
      {
        id: '101',
        game_type: '1',
        name: t('common.evoRealPerson'),
        rate: '0.00',
      },
      {
        id: '401',
        game_type: '4',
        name: t('common.IMSports'),
        rate: '0.00',
      },
      {
        id: '412',
        game_type: '4',
        name: t('common.ABSports'),
        rate: '0.00',
      },
      {
        id: '422',
        game_type: '4',
        name: t('common.CDSports'),
        rate: '0.00',
      },
      {
        id: '432',
        game_type: '4',
        name: t('common.EFSports'),
        rate: '0.00',
      },
      {
        id: '302',
        game_type: '3',
        name: t('common.EVOElectronics'),
        rate: '0.00',
      },
      {
        id: '301',
        game_type: '3',
        name: t('common.PGElectronics'),
        rate: '0.00',
      },
    ],
  },
  {
    level: '6',
    rebate_config: [
      {
        id: '101',
        game_type: '1',
        name: t('common.evoRealPerson'),
        rate: '0.00',
      },
      {
        id: '401',
        game_type: '4',
        name: t('common.IMSports'),
        rate: '0.00',
      },
      {
        id: '412',
        game_type: '4',
        name: t('common.ABSports'),
        rate: '0.00',
      },
      {
        id: '422',
        game_type: '4',
        name: t('common.CDSports'),
        rate: '0.00',
      },
      {
        id: '432',
        game_type: '4',
        name: t('common.EFSports'),
        rate: '0.00',
      },
      {
        id: '302',
        game_type: '3',
        name: t('common.EVOElectronics'),
        rate: '0.00',
      },
      {
        id: '301',
        game_type: '3',
        name: t('common.PGElectronics'),
        rate: '0.00',
      },
    ],
  },
  {
    level: '10',
    rebate_config: [
      {
        id: '101',
        game_type: '1',
        name: t('common.evoRealPerson'),
        rate: '0.00',
      },
      {
        id: '401',
        game_type: '4',
        name: t('common.IMSports'),
        rate: '0.00',
      },
      {
        id: '412',
        game_type: '4',
        name: t('common.ABSports'),
        rate: '0.00',
      },
      {
        id: '422',
        game_type: '4',
        name: t('common.CDSports'),
        rate: '0.00',
      },
      {
        id: '432',
        game_type: '4',
        name: t('common.EFSports'),
        rate: '0.00',
      },
      {
        id: '302',
        game_type: '3',
        name: t('common.EVOElectronics'),
        rate: '0.00',
      },
      {
        id: '301',
        game_type: '3',
        name: t('common.PGElectronics'),
        rate: '0.00',
      },
    ],
  },
  {
    level: '0',
    rebate_config: [
      {
        id: '101',
        game_type: '1',
        name: t('common.evoRealPerson'),
        rate: '78',
      },
      {
        id: '401',
        game_type: '4',
        name: t('common.IMSports'),
        rate: '8',
      },
      {
        id: '412',
        game_type: '4',
        name: t('common.ABSports'),
        rate: '2',
      },
      {
        id: '422',
        game_type: '4',
        name: t('common.CDSports'),
        rate: '7',
      },
      {
        id: '432',
        game_type: '4',
        name: t('common.EFSports'),
        rate: '8',
      },
      {
        id: '302',
        game_type: '3',
        name: t('common.EVOElectronics'),
        rate: '0.00',
      },
      {
        id: '301',
        game_type: '3',
        name: t('common.PGElectronics'),
        rate: '0.00',
      },
    ],
  },
  {
    level: '1',
    rebate_config: [
      {
        id: '101',
        game_type: '1',
        name: t('common.evoRealPerson'),
        rate: '7',
      },
      {
        id: '401',
        game_type: '4',
        name: t('common.IMSports'),
        rate: '45',
      },
      {
        id: '412',
        game_type: '4',
        name: t('common.ABSports'),
        rate: '5',
      },
      {
        id: '422',
        game_type: '4',
        name: t('common.CDSports'),
        rate: '3',
      },
      {
        id: '432',
        game_type: '4',
        name: t('common.EFSports'),
        rate: '1',
      },
      {
        id: '302',
        game_type: '3',
        name: t('common.EVOElectronics'),
        rate: '8',
      },
      {
        id: '301',
        game_type: '3',
        name: t('common.PGElectronics'),
        rate: '78',
      },
    ],
  },
  {
    level: '4',
    rebate_config: [
      {
        id: '101',
        game_type: '1',
        name: t('common.evoRealPerson'),
        rate: '0.00',
      },
      {
        id: '401',
        game_type: '4',
        name: t('common.IMSports'),
        rate: '0.00',
      },
      {
        id: '412',
        game_type: '4',
        name: t('common.ABSports'),
        rate: '0.00',
      },
      {
        id: '422',
        game_type: '4',
        name: t('common.CDSports'),
        rate: '0.00',
      },
      {
        id: '432',
        game_type: '4',
        name: t('common.EFSports'),
        rate: '0.00',
      },
      {
        id: '302',
        game_type: '3',
        name: t('common.EVOElectronics'),
        rate: '0.00',
      },
      {
        id: '301',
        game_type: '3',
        name: t('common.PGElectronics'),
        rate: '0.00',
      },
    ],
  },
  {
    level: '7',
    rebate_config: [
      {
        id: '401',
        game_type: '4',
        name: t('common.IMSports'),
        rate: '45',
      },
      {
        id: '412',
        game_type: '4',
        name: t('common.ABSports'),
        rate: '0.00',
      },
      {
        id: '422',
        game_type: '4',
        name: t('common.CDSports'),
        rate: '0.00',
      },
      {
        id: '432',
        game_type: '4',
        name: t('common.EFSports'),
        rate: '0.00',
      },
      {
        id: '302',
        game_type: '3',
        name: t('common.EVOElectronics'),
        rate: '0.00',
      },
      {
        id: '301',
        game_type: '3',
        name: t('common.PGElectronics'),
        rate: '0.00',
      },
      {
        id: '101',
        game_type: '1',
        name: t('common.evoRealPerson'),
        rate: '0.00',
      },
    ],
  },
];

export const testData1 = [
  {
    vipName: 'VIP0',
    game1: '78',
    game2: '4',
    game3: '4',
    game4: '4',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP1',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP2',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP3',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP4',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP4',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP6',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP7',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP8',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP9',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
  {
    vipName: 'VIP10',
    game1: '0',
    game2: '0',
    game3: '0',
    game4: '0',
    game5: '0',
    game6: '0',
    game7: '0',
  },
];
//js将details数组变成testData1
//比如level变成vipName，level的值赋值给vipName，其次game1对应rebate_config里面第一个rate值，game2对应rebate_config里面第二个rate值，game3对应rebate_config里面第三个rate值，game4对应rebate_config里面第四个rate值，game5对应rebate_config里面第五个rate值，game6对应rebate_config里面第六个rate值，game7对应rebate_config里面第七个rate值

export const newDeatil = [
  {
    vipName: 'VIP7',
    game1: '45',
    game2: '0.00',
    game3: '0.00',
    game4: '0.00',
    game5: '0.00',
    game6: '0.00',
    game7: '0.00',
  },
  {
    vipName: 'VIP9',
    game1: '78',
    game2: '8',
    game3: '9',
    game4: '36',
    game5: '1',
    game6: '1',
    game7: '12',
  },
  {
    vipName: 'VIP10',
    game1: '0.00',
    game2: '0.00',
    game3: '0.00',
    game4: '0.00',
    game5: '0.00',
    game6: '0.00',
    game7: '0.00',
  },
  {
    vipName: 'VIP2',
    game1: '0.00',
    game2: '0.00',
    game3: '0.00',
    game4: '0.00',
    game5: '0.00',
    game6: '0.00',
    game7: '0.00',
  },
  {
    vipName: 'VIP4',
    game1: '0.00',
    game2: '0.00',
    game3: '0.00',
    game4: '0.00',
    game5: '0.00',
    game6: '0.00',
    game7: '0.00',
  },
  {
    vipName: 'VIP6',
    game1: '0.00',
    game2: '0.00',
    game3: '0.00',
    game4: '0.00',
    game5: '0.00',
    game6: '0.00',
    game7: '0.00',
  },
  {
    vipName: 'VIP5',
    game1: '0.00',
    game2: '0.00',
    game3: '0.00',
    game4: '0.00',
    game5: '0.00',
    game6: '0.00',
    game7: '0.00',
  },
  {
    vipName: 'VIP8',
    game1: '0.00',
    game2: '0.00',
    game3: '0.00',
    game4: '0.00',
    game5: '0.00',
    game6: '0.00',
    game7: '0.00',
  },
  {
    vipName: 'VIP0',
    game1: '78',
    game2: '8',
    game3: '2',
    game4: '7',
    game5: '8',
    game6: '0.00',
    game7: '0.00',
  },
  {
    vipName: 'VIP1',
    game1: '7',
    game2: '45',
    game3: '5',
    game4: '3',
    game5: '1',
    game6: '8',
    game7: '78',
  },
  {
    vipName: 'VIP3',
    game1: '45',
    game2: '0.00',
    game3: '0.00',
    game4: '0.00',
    game5: '0.00',
    game6: '0.00',
    game7: '0.00',
  },
];

//js排序，按照vipName的值VIP1排到VIP10

export const listNew = [
  {
    id: '101',
    en_name: 'EVO Casino',
    game_type: '1',
    zh_name: 'EVO真人',
    pt_name: 'EVO Casino',
    vn_name: 'EVO Casino',
    th_name: 'EVO Casino',
    name: 'EVO真人',
    rate: '',
  },
  {
    id: '102',
    en_name: 'PP Casino',
    game_type: '1',
    zh_name: 'PP真人',
    pt_name: 'PP Casino',
    vn_name: 'PP Casino',
    th_name: 'PP Casino',
    name: 'PP真人',
    rate: '',
  },
  {
    id: '301',
    en_name: 'PG Slot',
    game_type: '3',
    zh_name: 'PG电子',
    pt_name: 'PG Slot',
    vn_name: 'PG Slot',
    th_name: 'PG Slot',
    name: 'PG电子',
    rate: '',
  },
  {
    id: '302',
    en_name: 'EVO Slot',
    game_type: '3',
    zh_name: 'EVO电子',
    pt_name: 'EVO Slot',
    vn_name: 'EVO Slot',
    th_name: 'EVO Slot',
    name: 'EVO电子',
    rate: '',
  },
  {
    id: '303',
    en_name: 'PP Slot',
    game_type: '3',
    zh_name: 'PP电子',
    pt_name: 'PP Slot',
    vn_name: 'PP Slot',
    th_name: 'PP Slot',
    name: 'PP电子',
    rate: '',
  },
  {
    id: '401',
    en_name: 'IM Sport',
    game_type: '4',
    zh_name: 'IM体育',
    pt_name: 'IM Sport',
    vn_name: 'IM Sport',
    th_name: 'IM Sport',
    name: 'IM体育',
    rate: '',
  },
];

export const listNew2 = [
  {
    id: '101',
    en_name: 'EVO Casino',
    game_type: '1',
    zh_name: 'EVO真人',
    pt_name: 'EVO Casino',
    vn_name: 'EVO Casino',
    th_name: 'EVO Casino',
    name: 'EVO真人',
    rate: '4',
  },
  {
    id: '301',
    en_name: 'Slot PG',
    game_type: '3',
    zh_name: 'PG电子',
    pt_name: 'Slot PG',
    vn_name: 'Slot PG',
    th_name: 'Slot PG',
    name: 'PG电子',
    rate: '10',
  },
  {
    id: '302',
    en_name: 'Slot EVO',
    game_type: '3',
    zh_name: 'EVO电子',
    pt_name: 'Slot EVO',
    vn_name: 'Slot EVO',
    th_name: 'Slot EVO',
    name: 'EVO电子',
    rate: '10',
  },
  {
    id: '303',
    en_name: 'Slot PP',
    game_type: '3',
    zh_name: 'PP电子',
    pt_name: 'Slot PP',
    vn_name: 'Slot PP',
    th_name: 'Slot PP',
    name: 'PP电子',
    rate: '10',
  },
  {
    id: '401',
    en_name: 'IM Sport',
    game_type: '4',
    zh_name: 'IM体育',
    pt_name: 'IM Sport',
    vn_name: 'IM Sport',
    th_name: 'IM Sport',
    name: 'IM体育',
    rate: '10',
  },
];

// 遍历listNew，用listNew的id和listNew2的id进行对比，如果id相同，则不返回，如果有id不同的元素，应该返回出去

export const lisU = [
  {
    id: '101',
    en_name: 'EVO Casino',
    game_type: '1',
    zh_name: 'EVO真人',
    pt_name: 'EVO Casino',
    vn_name: 'EVO Casino',
    th_name: 'EVO Casino',
    name: 'EVO真人',
    rate: '9',
  },
  {
    id: '301',
    en_name: 'Slot PG',
    game_type: '3',
    zh_name: 'PG电子',
    pt_name: 'Slot PG',
    vn_name: 'Slot PG',
    th_name: 'Slot PG',
    name: 'PG电子',
    rate: '9',
  },
  {
    id: '302',
    en_name: 'Slot EVO',
    game_type: '3',
    zh_name: 'EVO电子',
    pt_name: 'Slot EVO',
    vn_name: 'Slot EVO',
    th_name: 'Slot EVO',
    name: 'EVO电子',
    rate: '9',
  },
  {
    id: '303',
    en_name: 'Slot PP',
    game_type: '3',
    zh_name: 'PP电子',
    pt_name: 'Slot PP',
    vn_name: 'Slot PP',
    th_name: 'Slot PP',
    name: 'PP电子',
    rate: '9',
  },
  {
    id: '401',
    en_name: 'IM Sport',
    game_type: '4',
    zh_name: 'IM体育',
    pt_name: 'IM Sport',
    vn_name: 'IM Sport',
    th_name: 'IM Sport',
    name: 'IM体育',
    rate: '9',
  },
  {
    id: '102',
    en_name: 'PP Casino',
    game_type: '1',
    zh_name: 'PP真人',
    pt_name: 'PP Casino',
    vn_name: 'PP Casino',
    th_name: 'PP Casino',
    name: 'PP真人',
    rate: '',
  },
];
